### ISSUE TITLE
Cannot checkout repo due to Manifest Invalid Revision Error

### ISSUE THREAD

**Issue by lisandrocarmona** [crdroidandroid/android_hardware_xiaomi#1]
While syncing the repo, I cannot pass this error:

`Cannot checkout crdroidandroid/android_hardware_xiaomi: ManifestInvalidRevisionError: revision 13.0 in crdroidandroid/android_hardware_xiaomi not found`

Although revision 13.0 is the default one for this repo.
What am I doing wrong?

**Comment by gwolf2u** [comment]
Delete project from .repo/projects as well as hardware folder and resync
Issue is local, so closing this
