### ISSUE TITLE
Cannot find framework matrix at FCM version 4.

### ISSUE THREAD

**Issue by 0mew** [crdroidandroid/android_hardware_xiaomi#3]
android.hardware.ir@1.0::IConsumerIr/default
  android.hardware.media.omx@1.0::IOmx/default
  android.hardware.media.omx@1.0::IOmxStore/default
  android.hardware.memtrack@1.0::IMemtrack/default
  android.hardware.nfc@1.2::INfc/default
  android.hardware.power.IPower/default (@4)
  android.hardware.sensors@1.0::ISensors/default
  android.hardware.soundtrigger@2.2::ISoundTriggerHw/default
  android.hardware.tetheroffload.config@1.0::IOffloadConfig/default
  android.hardware.tetheroffload.control@1.0::IOffloadControl/default
  android.hardware.wifi.IWifi/default (@2)
  android.hardware.wifi.hostapd.IHostapd/default (@2)
  android.hardware.wifi.supplicant.ISupplicant/default (@3)
ERROR: No such file or directory: Cannot find framework matrix at FCM version 4.: No such f
ile or directory
21:27:15 ninja failed with: exit status 1

I encounter this problem while compiling the rom.

**Comment by gwolf2u** [comment]
DT issue
Not from this repo
